name: Pipeline CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Pobierz kod źródłowy
      uses: actions/checkout@v3

    - name: Wyświetl zawartość katalogu roboczego
      run: ls -la

    - name: Zainstaluj Pythona
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Zainstaluj zależności z requirements.txt
      working-directory: ${{ github.workspace }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sprawdź jakość kodu (flake8)
      working-directory: ${{ github.workspace }}
      run: flake8 NewCalculator.py

    - name: Uruchom testy (pytest)
      working-directory: ${{ github.workspace }}
      run: pytest

