name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kodu
      uses: actions/checkout@v3

    - name: Debug – pokaż zawartość katalogu
      run: ls -la

    - name: Ustaw wersję Pythona
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalacja zależności
      working-directory: ${{ github.workspace }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sprawdzenie jakości kodu (flake8)
      working-directory: ${{ github.workspace }}
      run: |
        flake8 NewCalculator.py

    - name: Uruchomienie testów (pytest)
      working-directory: ${{ github.workspace }}
      run: |
        pytest

