name: CI/CD dla kalkulatora online

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Pobierz kod
      uses: actions/checkout@v3

    - name: Sprawdź strukturę katalogu
      run: ls -la docs/

    - name: Sprawdź poprawność pliku HTML
      run: |
        if [ ! -f docs/calculator.html ]; then
          echo "Brak pliku calculator.html!"
          exit 1
        fi

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Wdróż stronę na GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

    - name: Health-check: Sprawdź dostępność kalkulatora
      run: |
        echo "Sprawdzam stronę kalkulatora..."
        sleep 10  # chwilka na propagację zmian
        curl -s -o /dev/null -w "%{http_code}" https://andrew76999.github.io/ZadanieDomowe/index.html | grep 200

